USE MASTER 
GO

CREATE DATABASE ANDROID

USE ANDROID
GO

CREATE TABLE TELEFONOS(
CODIGO INT PRIMARY KEY,
MARCA VARCHAR (100) NOT NULL,
MODELO VARCHAR (100) NOT NULL)

INSERT INTO TELEFONOS (CODIGO, MARCA, MODELO)
VALUES (123, 'SAMSUNG', 'SM-00');

Select CODIGO, MARCA, MODELO from TELEFONOS

EXECUTE xp_regread
@rootkey = 'HKEY_LOCAL_MACHINE',
@key = 'SOFTWARE\Microsoft\Microsoft SQL Server',
@value_name = 'InstalledInstances'